### ISSUE TITLE
Incompatibility with future Java versions

### ISSUE THREAD

**Issue by embeddedt** [qruet/AnvilLot#14]
**Server Version**
Purpur git-Purpur-1084

**Plugin Version**

v3.4_03-b5

**Describe the bug**

There is an illegal reflective accesses which is blocked by default in Java 16+. In Minecraft 1.17 this will be the default version of Java.

**To Reproduce**

Install the plugin and run the server.

```
WARNING: An illegal reflective access operation has occurred                          
WARNING: Illegal reflective access using Lookup on dev.qruet.anvillot.util.jdk1_14.ReflectionUtils (file:plugins/AnvilLot.jar) to class java.lang.reflect.Field
WARNING: Please consider reporting this to the maintainers of dev.qruet.anvillot.util.jdk1_14.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release                   
```

**Comment by qruet** [comment]
Thank you for the report. There isn't much I can do about this as of right now since certain fields are necessary to manipulate to allow for the features that exist in the plugin. Those fields can't be manipulated without reflection. I am hoping there will be some design changes with the 1.17 update that will allow for manipulation of those fields, however, until then - there's nothing I can really do until I have the complete update in my hands.

**Comment by embeddedt** [comment]
Thanks for the response!

As a note for future readers: the workaround for Java 16 is to add `--illegal-access=permit` to the server JVM flags.

**Comment by qruet** [comment]
This issue was patched a while ago however I never got around to dropping those modules. Next commit should reflect this change.
