### ISSUE TITLE
Modify the repair cost of an anvil without limits

### ISSUE THREAD

**Issue by IanWPG** [qruet/AnvilLot#4]
**Server Version**
git-Paper-156

**Plugin Version**
What version of MaxRepairCost are you using?
2.136
**Describe the bug**
Not a bug I don't think, the description says you can modify it without limits? Lowest the can set the repair cost to is 1xp, how can I make it require 0xp?

**To Reproduce**
N/A

**Media**
N/A

**Additional context**
N/A

**Comment by Geeveloper** [comment]
I will look into this as I may have never actually considered adding it yet as an option to make the costs completely removable.

**Comment by IanWPG** [comment]
> I will look into this as I may have never actually considered adding it yet as an option to make the costs completely removable.

No worries, it's not a big requirement of mine was curious if there was a way to set it or if it was never added as an option. You can safely put this on a low priority task as killing a simple cow(s) will get 1xp :) Will be the cherry on top for me as base materials for repair seems fair as a cost having XP cost along side it seems unreasonable to me to me lol and we already have enchanting table expense I have not modded that so to me IMO balances out.

**Comment by Geeveloper** [comment]
Spent a bit of time looking to see what was preventing items from being repaired with a cost set to 0 and I found a check that prevents setting repair costs to less then 1. This check is dug in pretty deep into spigot's source code for handling Anvil Inventories so I will have to completely rewrite the way spigot would be handling inventories instead of just slightly hacking a few values. This would in general bring many benefits but will take time so I probably won't be able to push out a solution just yet to your problem, but I'll try pushing out a major update that should resolve this issue sometime hopefully soon.

**Comment by qruet** [comment]
Setting cost to 0 is now possible with the latest pre-releases.
