### ISSUE TITLE
Illegal reflective access warning

### ISSUE THREAD

**Issue by fafrd** [qruet/AnvilLot#6]
**Server Version**
What spigot/paper/craftbukkit/etc. version are you using?

This server is running Paper version git-Paper-132 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)  

**Plugin Version**
What version of MaxRepairCost are you using?

latest, bab9f25df10dfbc199ce1912e1d8d2c72620f1bd

**Describe the bug**
The following warning shows in the log:

```
Mar 28 08:06:26 fuzz python3[8419]: WARNING: An illegal reflective access operation has occurred
Mar 28 08:06:26 fuzz python3[8419]: WARNING: Illegal reflective access by me.geekles.repaircost.listeners.AnvilManagementListener (file:/home/minecraft/gamesrotation/plugins/MaxRepairCost.jar) to field java.lang.reflect.Field.modifiers
Mar 28 08:06:26 fuzz python3[8419]: WARNING: Please consider reporting this to the maintainers of me.geekles.repaircost.listeners.AnvilManagementListener
Mar 28 08:06:26 fuzz python3[8419]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Mar 28 08:06:26 fuzz python3[8419]: WARNING: All illegal access operations will be denied in a future release 
```

**Comment by qruet** [comment]
Sorry for the delayed response but this issue is a known issue that unfortunately comes with Java version 11. This isn't an issue, fortunately, that affects the plugin's performance in any way and is only a suggestive error provided by Java since version 11. Versions Java 12 - 14 I was able to avoid this issue due to new tools implemented but that does not exist prior to 12. I can not quite get rid of this error from popping up on servers using Java 11 without totally suppressing errors completely which would be bad for debugging purposes and would affect the entire server, not just the plugin's own errors. My only recommendation is to ignore it or update to a later version of Java.
